--
-- PostgreSQL database dump
--

\restrict o03f5XVRXCoocBTqcOgTJahNsaiXk5onsEV6crVbT7hKuT2S5dgG7pepmLlegR9

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.2

-- Started on 2026-07-15 15:53:09

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 889 (class 1247 OID 16397)
-- Name: tipo_movimiento_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.tipo_movimiento_enum AS ENUM (
    'ENTRADA',
    'SALIDA'
);


ALTER TYPE public.tipo_movimiento_enum OWNER TO postgres;

--
-- TOC entry 255 (class 1255 OID 25042)
-- Name: fn_automatizar_kardex_cancelacion(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.fn_automatizar_kardex_cancelacion() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    r_detalle RECORD;
BEGIN
    -- Si el estado cambia de 1 (Procesada) a 0 (Cancelada)
    IF (OLD.estado = 1 AND NEW.estado = 0) THEN
        FOR r_detalle IN SELECT id_producto, cantidad FROM public.detalles_ventas WHERE id_venta = NEW.id LOOP
            INSERT INTO public.inventario (id_producto, tipo_movimiento, cantidad, fecha)
            VALUES (r_detalle.id_producto, 'ENTRADA', r_detalle.cantidad, CURRENT_TIMESTAMP);
        END LOOP;
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.fn_automatizar_kardex_cancelacion() OWNER TO postgres;

--
-- TOC entry 256 (class 1255 OID 25040)
-- Name: fn_automatizar_kardex_venta(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.fn_automatizar_kardex_venta() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_afecta BOOLEAN;
BEGIN
    IF (TG_OP = 'INSERT') THEN
        SELECT COALESCE(v.afecta_inventario, TRUE) INTO v_afecta
        FROM public.ventas v WHERE v.id = NEW.id_venta;

        IF v_afecta THEN
            INSERT INTO public.inventario (id_producto, tipo_movimiento, cantidad, fecha)
            VALUES (NEW.id_producto, 'SALIDA', NEW.cantidad, CURRENT_TIMESTAMP);
        END IF;
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.fn_automatizar_kardex_venta() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 254 (class 1259 OID 33256)
-- Name: caja_sesion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caja_sesion (
    id bigint NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_apertura timestamp(6) without time zone NOT NULL,
    fecha_cierre timestamp(6) without time zone,
    monto_apertura numeric(10,2) NOT NULL,
    monto_cierre numeric(10,2),
    id_usuario_apertura bigint NOT NULL,
    id_usuario_cierre bigint
);


ALTER TABLE public.caja_sesion OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 33255)
-- Name: caja_sesion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caja_sesion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caja_sesion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16480)
-- Name: categorias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion character varying(255),
    estado integer DEFAULT 1
);


ALTER TABLE public.categorias OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16479)
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.categorias_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.categorias_id_seq OWNER TO postgres;

--
-- TOC entry 5271 (class 0 OID 0)
-- Dependencies: 230
-- Name: categorias_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.categorias_id_seq OWNED BY public.categorias.id;


--
-- TOC entry 227 (class 1259 OID 16456)
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    dni_ruc character varying(20) NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion character varying(255),
    dni character varying(20),
    email character varying(100),
    telefono character varying(20),
    estado integer NOT NULL
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16455)
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.clientes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.clientes_id_seq OWNER TO postgres;

--
-- TOC entry 5272 (class 0 OID 0)
-- Dependencies: 226
-- Name: clientes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.clientes_id_seq OWNED BY public.clientes.id;


--
-- TOC entry 243 (class 1259 OID 16579)
-- Name: cuentas_cobrar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuentas_cobrar (
    id bigint NOT NULL,
    id_cliente bigint,
    id_venta bigint,
    saldo_pendiente numeric(10,2),
    estado character varying(20),
    fecha_creacion timestamp(6) without time zone,
    fecha_pago date
);


ALTER TABLE public.cuentas_cobrar OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16578)
-- Name: cuentas_cobrar_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cuentas_cobrar_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cuentas_cobrar_id_seq OWNER TO postgres;

--
-- TOC entry 5273 (class 0 OID 0)
-- Dependencies: 242
-- Name: cuentas_cobrar_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cuentas_cobrar_id_seq OWNED BY public.cuentas_cobrar.id;


--
-- TOC entry 245 (class 1259 OID 16597)
-- Name: cuentas_pagar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuentas_pagar (
    id bigint NOT NULL,
    id_proveedor bigint,
    monto_total numeric(10,2),
    saldo_pendiente numeric(10,2),
    estado character varying(20)
);


ALTER TABLE public.cuentas_pagar OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16596)
-- Name: cuentas_pagar_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cuentas_pagar_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cuentas_pagar_id_seq OWNER TO postgres;

--
-- TOC entry 5274 (class 0 OID 0)
-- Dependencies: 244
-- Name: cuentas_pagar_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cuentas_pagar_id_seq OWNED BY public.cuentas_pagar.id;


--
-- TOC entry 250 (class 1259 OID 25063)
-- Name: detalles_pedidos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalles_pedidos (
    id bigint NOT NULL,
    id_pedido bigint NOT NULL,
    id_producto bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL
);


ALTER TABLE public.detalles_pedidos OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 25062)
-- Name: detalles_pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.detalles_pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.detalles_pedidos_id_seq OWNER TO postgres;

--
-- TOC entry 5275 (class 0 OID 0)
-- Dependencies: 249
-- Name: detalles_pedidos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.detalles_pedidos_id_seq OWNED BY public.detalles_pedidos.id;


--
-- TOC entry 235 (class 1259 OID 16510)
-- Name: detalles_tecnicos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalles_tecnicos (
    id integer NOT NULL,
    id_producto bigint,
    tipo_rosca character varying(50),
    tipo_cabeza character varying(50),
    longitud character varying(50)
);


ALTER TABLE public.detalles_tecnicos OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16509)
-- Name: detalles_tecnicos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.detalles_tecnicos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.detalles_tecnicos_id_seq OWNER TO postgres;

--
-- TOC entry 5276 (class 0 OID 0)
-- Dependencies: 234
-- Name: detalles_tecnicos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.detalles_tecnicos_id_seq OWNED BY public.detalles_tecnicos.id;


--
-- TOC entry 239 (class 1259 OID 16543)
-- Name: detalles_ventas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalles_ventas (
    id bigint NOT NULL,
    id_venta bigint NOT NULL,
    id_producto bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_venta numeric(10,2) NOT NULL,
    descuento numeric(10,2) DEFAULT 0.00 NOT NULL,
    subtotal numeric(10,2) DEFAULT 0.00 NOT NULL
);


ALTER TABLE public.detalles_ventas OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16542)
-- Name: detalles_ventas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.detalles_ventas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.detalles_ventas_id_seq OWNER TO postgres;

--
-- TOC entry 5277 (class 0 OID 0)
-- Dependencies: 238
-- Name: detalles_ventas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.detalles_ventas_id_seq OWNED BY public.detalles_ventas.id;


--
-- TOC entry 241 (class 1259 OID 16563)
-- Name: inventario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario (
    id integer NOT NULL,
    id_producto bigint,
    tipo_movimiento public.tipo_movimiento_enum NOT NULL,
    cantidad integer NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.inventario OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16562)
-- Name: inventario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.inventario_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.inventario_id_seq OWNER TO postgres;

--
-- TOC entry 5278 (class 0 OID 0)
-- Dependencies: 240
-- Name: inventario_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.inventario_id_seq OWNED BY public.inventario.id;


--
-- TOC entry 252 (class 1259 OID 33211)
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificaciones (
    id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    leida boolean NOT NULL,
    mensaje character varying(500) NOT NULL,
    tipo character varying(50) NOT NULL,
    titulo character varying(200) NOT NULL,
    url_destino character varying(500),
    id_cuenta_cobrar bigint,
    id_cuenta_pagar bigint,
    id_pedido bigint,
    id_producto bigint,
    id_usuario bigint NOT NULL
);


ALTER TABLE public.notificaciones OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 33210)
-- Name: notificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16412)
-- Name: opciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.opciones (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    ruta character varying(100),
    icono character varying(50)
);


ALTER TABLE public.opciones OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16411)
-- Name: opciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.opciones_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.opciones_id_seq OWNER TO postgres;

--
-- TOC entry 5279 (class 0 OID 0)
-- Dependencies: 221
-- Name: opciones_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.opciones_id_seq OWNED BY public.opciones.id;


--
-- TOC entry 248 (class 1259 OID 25045)
-- Name: pedidos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedidos (
    id bigint NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_cliente bigint NOT NULL,
    total numeric(10,2) NOT NULL,
    estado character varying(20) DEFAULT 'PENDIENTE'::character varying NOT NULL
);


ALTER TABLE public.pedidos OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 25044)
-- Name: pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pedidos_id_seq OWNER TO postgres;

--
-- TOC entry 5280 (class 0 OID 0)
-- Dependencies: 247
-- Name: pedidos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pedidos_id_seq OWNED BY public.pedidos.id;


--
-- TOC entry 246 (class 1259 OID 16622)
-- Name: perfil_opcion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.perfil_opcion (
    id_perfil bigint NOT NULL,
    id_opcion bigint NOT NULL
);


ALTER TABLE public.perfil_opcion OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16402)
-- Name: perfiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.perfiles (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion character varying(255),
    estado integer DEFAULT 1
);


ALTER TABLE public.perfiles OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16401)
-- Name: perfiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.perfiles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.perfiles_id_seq OWNER TO postgres;

--
-- TOC entry 5281 (class 0 OID 0)
-- Dependencies: 219
-- Name: perfiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.perfiles_id_seq OWNED BY public.perfiles.id;


--
-- TOC entry 223 (class 1259 OID 16420)
-- Name: perfiles_opciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.perfiles_opciones (
    id_perfil integer NOT NULL,
    id_opcion integer NOT NULL
);


ALTER TABLE public.perfiles_opciones OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16489)
-- Name: productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    id_categoria bigint,
    id_proveedor bigint,
    precio numeric(10,2) NOT NULL,
    stock integer DEFAULT 0,
    descripcion text,
    estado integer DEFAULT 1,
    fecha_registro timestamp(6) without time zone,
    imagen character varying(255),
    precio_compra numeric(10,2),
    precio_venta numeric(10,2) NOT NULL,
    stock_minimo integer DEFAULT 0
);


ALTER TABLE public.productos OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16488)
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.productos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.productos_id_seq OWNER TO postgres;

--
-- TOC entry 5282 (class 0 OID 0)
-- Dependencies: 232
-- Name: productos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.productos_id_seq OWNED BY public.productos.id;


--
-- TOC entry 229 (class 1259 OID 16468)
-- Name: proveedores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proveedores (
    id bigint NOT NULL,
    ruc character varying(20) NOT NULL,
    nombre character varying(150) NOT NULL,
    correo character varying(100),
    direccion character varying(255),
    estado integer DEFAULT 1,
    telefono character varying(50),
    documento character varying(20)
);


ALTER TABLE public.proveedores OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16467)
-- Name: proveedores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.proveedores_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.proveedores_id_seq OWNER TO postgres;

--
-- TOC entry 5283 (class 0 OID 0)
-- Dependencies: 228
-- Name: proveedores_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.proveedores_id_seq OWNED BY public.proveedores.id;


--
-- TOC entry 225 (class 1259 OID 16438)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    usuario character varying(50) NOT NULL,
    clave character varying(255) NOT NULL,
    id_perfil bigint,
    correo character varying(255) NOT NULL,
    estado integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16437)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuarios_id_seq OWNER TO postgres;

--
-- TOC entry 5284 (class 0 OID 0)
-- Dependencies: 224
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- TOC entry 237 (class 1259 OID 16523)
-- Name: ventas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ventas (
    id bigint NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_usuario bigint NOT NULL,
    id_cliente bigint NOT NULL,
    total numeric(10,2) NOT NULL,
    estado integer DEFAULT 1 NOT NULL,
    tipo_comprobante character varying(20) DEFAULT 'BOLETA'::character varying NOT NULL,
    serie character varying(10) DEFAULT 'B001'::character varying NOT NULL,
    numero_comprobante character varying(20) DEFAULT '00000001'::character varying NOT NULL,
    subtotal numeric(10,2) DEFAULT 0.00 NOT NULL,
    igv numeric(10,2) DEFAULT 0.00 NOT NULL,
    estado_documento character varying(20),
    comprobante_canje_id bigint,
    nota_origen_id bigint,
    afecta_inventario boolean DEFAULT true NOT NULL,
    metodo_pago character varying(30) DEFAULT 'EFECTIVO'::character varying,
    monto_efectivo numeric(10,2) DEFAULT 0.0,
    monto_tarjeta numeric(10,2) DEFAULT 0.0,
    monto_transferencia numeric(10,2) DEFAULT 0.0,
    monto_yape numeric(10,2) DEFAULT 0.0
);


ALTER TABLE public.ventas OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16522)
-- Name: ventas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ventas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ventas_id_seq OWNER TO postgres;

--
-- TOC entry 5285 (class 0 OID 0)
-- Dependencies: 236
-- Name: ventas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ventas_id_seq OWNED BY public.ventas.id;


--
-- TOC entry 4957 (class 2604 OID 16717)
-- Name: categorias id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias ALTER COLUMN id SET DEFAULT nextval('public.categorias_id_seq'::regclass);


--
-- TOC entry 4954 (class 2604 OID 24884)
-- Name: clientes id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes ALTER COLUMN id SET DEFAULT nextval('public.clientes_id_seq'::regclass);


--
-- TOC entry 4983 (class 2604 OID 33194)
-- Name: cuentas_cobrar id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas_cobrar ALTER COLUMN id SET DEFAULT nextval('public.cuentas_cobrar_id_seq'::regclass);


--
-- TOC entry 4984 (class 2604 OID 33202)
-- Name: cuentas_pagar id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas_pagar ALTER COLUMN id SET DEFAULT nextval('public.cuentas_pagar_id_seq'::regclass);


--
-- TOC entry 4988 (class 2604 OID 25066)
-- Name: detalles_pedidos id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_pedidos ALTER COLUMN id SET DEFAULT nextval('public.detalles_pedidos_id_seq'::regclass);


--
-- TOC entry 4963 (class 2604 OID 16513)
-- Name: detalles_tecnicos id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_tecnicos ALTER COLUMN id SET DEFAULT nextval('public.detalles_tecnicos_id_seq'::regclass);


--
-- TOC entry 4978 (class 2604 OID 24905)
-- Name: detalles_ventas id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_ventas ALTER COLUMN id SET DEFAULT nextval('public.detalles_ventas_id_seq'::regclass);


--
-- TOC entry 4981 (class 2604 OID 16566)
-- Name: inventario id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario ALTER COLUMN id SET DEFAULT nextval('public.inventario_id_seq'::regclass);


--
-- TOC entry 4951 (class 2604 OID 16609)
-- Name: opciones id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.opciones ALTER COLUMN id SET DEFAULT nextval('public.opciones_id_seq'::regclass);


--
-- TOC entry 4985 (class 2604 OID 25048)
-- Name: pedidos id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidos ALTER COLUMN id SET DEFAULT nextval('public.pedidos_id_seq'::regclass);


--
-- TOC entry 4949 (class 2604 OID 16629)
-- Name: perfiles id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfiles ALTER COLUMN id SET DEFAULT nextval('public.perfiles_id_seq'::regclass);


--
-- TOC entry 4959 (class 2604 OID 16692)
-- Name: productos id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos ALTER COLUMN id SET DEFAULT nextval('public.productos_id_seq'::regclass);


--
-- TOC entry 4955 (class 2604 OID 16757)
-- Name: proveedores id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores ALTER COLUMN id SET DEFAULT nextval('public.proveedores_id_seq'::regclass);


--
-- TOC entry 4952 (class 2604 OID 16647)
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- TOC entry 4964 (class 2604 OID 24931)
-- Name: ventas id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas ALTER COLUMN id SET DEFAULT nextval('public.ventas_id_seq'::regclass);


--
-- TOC entry 5265 (class 0 OID 33256)
-- Dependencies: 254
-- Data for Name: caja_sesion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.caja_sesion (id, estado, fecha_apertura, fecha_cierre, monto_apertura, monto_cierre, id_usuario_apertura, id_usuario_cierre) FROM stdin;
1	CERRADA	2026-07-03 09:08:36.64168	2026-07-07 09:24:48.664891	50.00	100.00	1	1
2	ABIERTA	2026-07-07 09:28:42.847716	\N	100.00	\N	1	\N
\.


--
-- TOC entry 5242 (class 0 OID 16480)
-- Dependencies: 231
-- Data for Name: categorias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categorias (id, nombre, descripcion, estado) FROM stdin;
1	Alicates	Alicates de presión, corte, universal y especialistas	1
2	Lubricantes	Aceites multiusos, aflojatodo y para motores	1
3	Aplicadores	Pistolas y aplicadores para silicona y calafateo	1
4	Automotriz	Herramientas especializadas para mecánica automotriz	1
5	Soldadura	Porta electrodos y accesorios para soldar	1
6	Medición	Flexómetros, niveles y cintas métricas	1
7	Llaves y Dados	Llaves combinadas, españolas, juegos de dados y matracas	1
8	Corte y Desbaste	Arcos de sierra, hojas de sierra, limas y cutters	1
9	Fijación y Remachado	Remachadoras manuales y remaches	1
10	Golpe y Fuerza	Martillos, combas, barretas y cinceles	1
11	Pintura y Acabados	Brochas, pinceles y rodillos	1
12	Destornilladores y Puntas	Destornilladores de pala, phillips y juegos de puntas	1
13	Equipamiento de Taller	Torquímetros, extractores y prensas	1
14	Pernos y Tuercas		1
\.


--
-- TOC entry 5238 (class 0 OID 16456)
-- Dependencies: 227
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clientes (id, dni_ruc, nombre, direccion, dni, email, telefono, estado) FROM stdin;
2	72091907	MONTUFAR MERMA	\N	\N	rmontufar@gmail.com	987456322	1
3	10710779681	MONTENEGRO SAMAME LUZ DE BELEN	-	\N	luzdebelen13@gmail.com		1
7	41681372	LUIS ANTONIO CHAFLOQUE AVELLANEDA	mi casa	\N	luzdebelen13@gmail.com	987456321	1
8	43156342123	ELMER SOSA CHERO		\N	ejemplo@gmail.com	987412563444555222	1
9	00000000	CLIENTE GENERAL	\N	\N	\N	\N	1
10	45129268	LUIS ALONSO MILLA ORIHUELA		\N			1
11	47105890	LEANDRA MARTINEZ LLOCLLE		\N			1
13	41575250	JULLIANA DEL PILAR SAMAME ALTAMIRANO		\N	julliana@gmail.com	978329692	1
14	40709584	LISSETTE CRISTINA SAMAME ALTAMIRANO		\N	lissettecris@gmail.com	926815661	1
15	74781665	ALMA SHARON YZQUIERDO SAMAME	\N	\N	alma@gmail.com	967693956	1
1	71077968	LUZ DE BELEN MONTENEGRO SAMAME	mi casa	\N	luzdebelen13@gmail.com	987456321	1
\.


--
-- TOC entry 5254 (class 0 OID 16579)
-- Dependencies: 243
-- Data for Name: cuentas_cobrar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuentas_cobrar (id, id_cliente, id_venta, saldo_pendiente, estado, fecha_creacion, fecha_pago) FROM stdin;
1	1	1	26.14	PENDIENTE	\N	\N
3	11	15	0.00	PAGADO	2026-06-07 17:41:11.322833	2026-08-06
5	1	18	27.18	PENDIENTE	2026-06-09 09:35:30.941938	2026-08-08
4	1	18	0.00	PAGADO	2026-06-09 09:35:30.931423	2026-07-09
2	11	15	0.00	PAGADO	2026-06-07 17:41:11.306899	2026-07-07
\.


--
-- TOC entry 5256 (class 0 OID 16597)
-- Dependencies: 245
-- Data for Name: cuentas_pagar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuentas_pagar (id, id_proveedor, monto_total, saldo_pendiente, estado) FROM stdin;
1	1	1000.00	900.00	PARCIAL
\.


--
-- TOC entry 5261 (class 0 OID 25063)
-- Dependencies: 250
-- Data for Name: detalles_pedidos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalles_pedidos (id, id_pedido, id_producto, cantidad, precio_unitario, subtotal) FROM stdin;
1	1	6	1	8.90	8.90
2	2	8	1	7.16	7.16
3	2	6	1	8.90	8.90
4	2	10	1	31.78	31.78
5	2	12	1	42.50	42.50
6	2	13	1	19.80	19.80
7	3	7	3	10.17	30.51
8	3	5	1	15.97	15.97
9	3	6	1	8.90	8.90
10	4	12	1	42.50	42.50
11	4	13	1	19.80	19.80
12	4	14	1	11.25	11.25
13	5	5	1	15.97	15.97
14	5	6	1	8.90	8.90
15	5	4	2	16.00	32.00
16	6	7	1	10.17	10.17
17	6	10	1	31.78	31.78
18	6	11	1	158.78	158.78
19	6	15	1	41.60	41.60
20	6	14	1	11.25	11.25
21	7	5	1	15.97	15.97
22	7	9	2	12.75	25.50
23	8	14	1	11.25	11.25
24	8	15	1	41.60	41.60
25	8	13	1	19.80	19.80
26	9	2	2	15.68	31.36
27	9	14	1	11.25	11.25
28	9	12	1	42.50	42.50
29	10	11	2	158.78	317.56
30	10	16	1	45.50	45.50
31	11	9	1	12.75	12.75
32	11	15	1	41.60	41.60
\.


--
-- TOC entry 5246 (class 0 OID 16510)
-- Dependencies: 235
-- Data for Name: detalles_tecnicos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalles_tecnicos (id, id_producto, tipo_rosca, tipo_cabeza, longitud) FROM stdin;
\.


--
-- TOC entry 5250 (class 0 OID 16543)
-- Dependencies: 239
-- Data for Name: detalles_ventas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalles_ventas (id, id_venta, id_producto, cantidad, precio_venta, descuento, subtotal) FROM stdin;
1	1	5	1	15.97	0.00	15.97
2	1	7	1	10.17	0.00	10.17
3	2	1	1	26.69	0.00	26.69
4	2	9	1	12.75	0.00	12.75
5	3	12	1	42.50	0.00	42.50
6	3	13	1	19.80	0.00	19.80
7	3	14	1	11.25	0.00	11.25
8	4	5	1	15.97	0.00	15.97
9	4	6	1	8.90	0.00	8.90
10	4	4	2	16.00	0.00	32.00
11	5	15	1	41.60	0.00	41.60
12	5	7	1	10.17	0.00	10.17
13	5	10	1	31.78	0.00	31.78
14	5	11	1	158.78	0.00	158.78
15	5	14	1	11.25	0.00	11.25
16	6	9	1	12.75	0.00	12.75
17	6	1	1	26.69	0.00	26.69
18	6	12	1	42.50	0.00	42.50
19	7	9	1	12.75	0.00	12.75
20	7	2	1	15.68	0.00	15.68
21	8	1	1	26.69	0.00	26.69
22	8	4	1	16.00	0.00	16.00
23	9	6	1	8.90	0.00	8.90
24	10	13	1	19.80	0.00	19.80
25	10	15	1	41.60	0.00	41.60
26	10	14	1	11.25	0.00	11.25
27	11	13	1	19.80	0.00	19.80
28	11	15	1	41.60	0.00	41.60
29	11	14	1	11.25	0.00	11.25
30	12	6	1	8.90	0.00	8.90
31	13	11	2	158.78	0.00	317.56
32	13	16	1	45.50	0.00	45.50
33	14	11	2	158.78	0.00	317.56
34	14	16	1	45.50	0.00	45.50
35	15	1	1	26.69	0.00	26.69
36	15	4	1	16.00	0.00	16.00
37	16	9	1	12.75	0.00	12.75
38	16	2	1	15.68	0.00	15.68
39	17	15	1	41.60	0.00	41.60
40	17	9	1	12.75	0.00	12.75
41	18	15	1	41.60	0.00	41.60
42	18	9	1	12.75	0.00	12.75
\.


--
-- TOC entry 5252 (class 0 OID 16563)
-- Dependencies: 241
-- Data for Name: inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario (id, id_producto, tipo_movimiento, cantidad, fecha) FROM stdin;
1	12	SALIDA	1	2026-05-29 09:34:06.11338
2	13	SALIDA	1	2026-05-29 09:34:06.11338
3	14	SALIDA	1	2026-05-29 09:34:06.11338
4	5	SALIDA	1	2026-06-02 09:40:06.224963
5	6	SALIDA	1	2026-06-02 09:40:06.224963
6	4	SALIDA	2	2026-06-02 09:40:06.224963
7	15	SALIDA	1	2026-06-02 09:41:56.253955
8	7	SALIDA	1	2026-06-02 09:41:56.253955
9	10	SALIDA	1	2026-06-02 09:41:56.253955
10	11	SALIDA	1	2026-06-02 09:41:56.253955
11	14	SALIDA	1	2026-06-02 09:41:56.253955
12	9	SALIDA	1	2026-06-05 09:09:05.366739
13	1	SALIDA	1	2026-06-05 09:09:05.366739
14	12	SALIDA	1	2026-06-05 09:09:05.366739
15	9	SALIDA	1	2026-06-05 09:22:57.664643
16	2	SALIDA	1	2026-06-05 09:22:57.664643
17	1	SALIDA	1	2026-06-05 09:24:28.045456
18	4	SALIDA	1	2026-06-05 09:24:28.045456
19	6	SALIDA	1	2026-06-06 22:02:53.215724
20	13	SALIDA	1	2026-06-06 22:03:20.182561
21	15	SALIDA	1	2026-06-06 22:03:20.182561
22	14	SALIDA	1	2026-06-06 22:03:20.182561
23	11	SALIDA	2	2026-06-07 15:22:47.115171
24	16	SALIDA	1	2026-06-07 15:22:47.115171
25	9	ENTRADA	1	2026-06-08 16:18:24.230494
26	2	ENTRADA	1	2026-06-08 16:18:24.230494
27	15	SALIDA	1	2026-06-09 09:31:38.178704
28	9	SALIDA	1	2026-06-09 09:31:38.178704
\.


--
-- TOC entry 5263 (class 0 OID 33211)
-- Dependencies: 252
-- Data for Name: notificaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notificaciones (id, fecha_creacion, leida, mensaje, tipo, titulo, url_destino, id_cuenta_cobrar, id_cuenta_pagar, id_pedido, id_producto, id_usuario) FROM stdin;
1	2026-06-07 13:56:26.097082	f	Nuevo saldo pendiente S/. 26.14 de LUZ DE BELEN MONTENEGRO	CUENTA_COBRAR	Cuenta por cobrar #1	/cuentas-cobrar/listar	1	\N	\N	\N	2
3	2026-06-07 13:56:26.118189	f	Nuevo saldo pendiente S/. 26.14 de LUZ DE BELEN MONTENEGRO	CUENTA_COBRAR	Cuenta por cobrar #1	/cuentas-cobrar/listar	1	\N	\N	\N	4
4	2026-06-07 13:56:26.126408	f	Nuevo saldo pendiente S/. 26.14 de LUZ DE BELEN MONTENEGRO	CUENTA_COBRAR	Cuenta por cobrar #1	/cuentas-cobrar/listar	1	\N	\N	\N	6
5	2026-06-07 13:56:26.13485	f	Nuevo saldo pendiente S/. 26.14 de LUZ DE BELEN MONTENEGRO	CUENTA_COBRAR	Cuenta por cobrar #1	/cuentas-cobrar/listar	1	\N	\N	\N	10
6	2026-06-07 13:57:39.336126	f	Obligación con Truper Servicios S.A. — saldo pendiente S/. 1000.00	CUENTA_PAGAR	Cuenta por pagar #1	/cuentas-pagar/listar	\N	1	\N	\N	2
8	2026-06-07 13:57:39.362147	f	Obligación con Truper Servicios S.A. — saldo pendiente S/. 1000.00	CUENTA_PAGAR	Cuenta por pagar #1	/cuentas-pagar/listar	\N	1	\N	\N	4
9	2026-06-07 13:57:39.37369	f	Obligación con Truper Servicios S.A. — saldo pendiente S/. 1000.00	CUENTA_PAGAR	Cuenta por pagar #1	/cuentas-pagar/listar	\N	1	\N	\N	6
10	2026-06-07 13:57:39.419705	f	Obligación con Truper Servicios S.A. — saldo pendiente S/. 1000.00	CUENTA_PAGAR	Cuenta por pagar #1	/cuentas-pagar/listar	\N	1	\N	\N	10
11	2026-06-07 14:01:48.827503	f	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 85.11	PEDIDO_NUEVO	Nuevo pedido #9	/pedidos/listar?pedido=9	\N	\N	9	\N	2
13	2026-06-07 14:01:48.859606	f	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 85.11	PEDIDO_NUEVO	Nuevo pedido #9	/pedidos/listar?pedido=9	\N	\N	9	\N	4
14	2026-06-07 14:01:48.887186	f	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 85.11	PEDIDO_NUEVO	Nuevo pedido #9	/pedidos/listar?pedido=9	\N	\N	9	\N	6
15	2026-06-07 14:01:48.897493	f	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 85.11	PEDIDO_NUEVO	Nuevo pedido #9	/pedidos/listar?pedido=9	\N	\N	9	\N	10
16	2026-06-07 15:21:16.819605	f	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 363.06	PEDIDO_NUEVO	Nuevo pedido #10	/pedidos/listar?pedido=10	\N	\N	10	\N	2
18	2026-06-07 15:21:16.837784	f	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 363.06	PEDIDO_NUEVO	Nuevo pedido #10	/pedidos/listar?pedido=10	\N	\N	10	\N	4
19	2026-06-07 15:21:16.847693	f	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 363.06	PEDIDO_NUEVO	Nuevo pedido #10	/pedidos/listar?pedido=10	\N	\N	10	\N	6
20	2026-06-07 15:21:16.856235	f	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 363.06	PEDIDO_NUEVO	Nuevo pedido #10	/pedidos/listar?pedido=10	\N	\N	10	\N	10
17	2026-06-07 15:21:16.828142	t	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 363.06	PEDIDO_NUEVO	Nuevo pedido #10	/pedidos/listar?pedido=10	\N	\N	10	\N	1
12	2026-06-07 14:01:48.84063	t	El cliente ALMA SHARON YZQUIERDO SAMAME registró un pedido por S/. 85.11	PEDIDO_NUEVO	Nuevo pedido #9	/pedidos/listar?pedido=9	\N	\N	9	\N	1
7	2026-06-07 13:57:39.349795	t	Obligación con Truper Servicios S.A. — saldo pendiente S/. 1000.00	CUENTA_PAGAR	Cuenta por pagar #1	/cuentas-pagar/listar	\N	1	\N	\N	1
2	2026-06-07 13:56:26.110636	t	Nuevo saldo pendiente S/. 26.14 de LUZ DE BELEN MONTENEGRO	CUENTA_COBRAR	Cuenta por cobrar #1	/cuentas-cobrar/listar	1	\N	\N	\N	1
21	2026-06-08 16:40:26.98343	f	Quedan 1 uds. (mínimo: 2) de "Extractor de resortes válvulas (14528)".	STOCK_BAJO	Stock bajo: Extractor de resortes válvulas (14528)	/inventario/listar	\N	\N	\N	11	2
22	2026-06-08 16:40:26.999604	f	Quedan 1 uds. (mínimo: 2) de "Extractor de resortes válvulas (14528)".	STOCK_BAJO	Stock bajo: Extractor de resortes válvulas (14528)	/inventario/listar	\N	\N	\N	11	1
23	2026-06-08 16:40:27.005665	f	Quedan 1 uds. (mínimo: 2) de "Extractor de resortes válvulas (14528)".	STOCK_BAJO	Stock bajo: Extractor de resortes válvulas (14528)	/inventario/listar	\N	\N	\N	11	6
24	2026-06-08 16:40:27.009126	f	Quedan 1 uds. (mínimo: 2) de "Extractor de resortes válvulas (14528)".	STOCK_BAJO	Stock bajo: Extractor de resortes válvulas (14528)	/inventario/listar	\N	\N	\N	11	10
25	2026-06-09 09:26:38.319204	f	Quedan 5 uds. (mínimo: 10) de "Juego de destornilladores 6 piezas (14140)".	STOCK_BAJO	Stock bajo: Juego de destornilladores 6 piezas (14140)	/inventario/listar	\N	\N	\N	16	2
26	2026-06-09 09:26:38.394865	f	Quedan 5 uds. (mínimo: 10) de "Juego de destornilladores 6 piezas (14140)".	STOCK_BAJO	Stock bajo: Juego de destornilladores 6 piezas (14140)	/inventario/listar	\N	\N	\N	16	1
27	2026-06-09 09:26:38.414809	f	Quedan 5 uds. (mínimo: 10) de "Juego de destornilladores 6 piezas (14140)".	STOCK_BAJO	Stock bajo: Juego de destornilladores 6 piezas (14140)	/inventario/listar	\N	\N	\N	16	6
28	2026-06-09 09:26:38.429511	f	Quedan 5 uds. (mínimo: 10) de "Juego de destornilladores 6 piezas (14140)".	STOCK_BAJO	Stock bajo: Juego de destornilladores 6 piezas (14140)	/inventario/listar	\N	\N	\N	16	10
29	2026-06-09 09:30:19.093003	f	El cliente LUZ DE BELEN MONTENEGRO SAMAME registró un pedido por S/. 54.35	PEDIDO_NUEVO	Nuevo pedido #11	/pedidos/listar?pedido=11	\N	\N	11	\N	2
30	2026-06-09 09:30:19.103054	f	El cliente LUZ DE BELEN MONTENEGRO SAMAME registró un pedido por S/. 54.35	PEDIDO_NUEVO	Nuevo pedido #11	/pedidos/listar?pedido=11	\N	\N	11	\N	1
31	2026-06-09 09:30:19.138141	f	El cliente LUZ DE BELEN MONTENEGRO SAMAME registró un pedido por S/. 54.35	PEDIDO_NUEVO	Nuevo pedido #11	/pedidos/listar?pedido=11	\N	\N	11	\N	6
32	2026-06-09 09:30:19.156253	f	El cliente LUZ DE BELEN MONTENEGRO SAMAME registró un pedido por S/. 54.35	PEDIDO_NUEVO	Nuevo pedido #11	/pedidos/listar?pedido=11	\N	\N	11	\N	10
\.


--
-- TOC entry 5233 (class 0 OID 16412)
-- Dependencies: 222
-- Data for Name: opciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.opciones (id, nombre, ruta, icono) FROM stdin;
1	Dashboard	/dashboard	bi-house-door-fill
2	Usuarios	/usuarios/listar	bi-people-fill
3	Perfiles	/perfiles/listar	bi-person-vcard-fill
4	Productos	/productos/listar	bi-box-fill
5	Categorías	/categorias/listar	bi-tag-fill
6	Proveedores	/proveedores/listar	bi-truck
7	Clientes	/clientes/listar	bi-person-badge-fill
8	Ventas	/ventas/notas/listar	bi-cart-fill
9	Inventario	/inventario/listar	bi-archive-fill
10	Pedidos	/pedidos/listar	bi-clock-history
11	Cuentas por Cobrar	/cuentas-cobrar/listar	bi-cash-stack
12	Cuentas por Pagar	/cuentas-pagar/listar	bi-wallet2
13	Control de Caja	/caja/listar	bi-wallet2
14	Reportes y Pagos	/reportes/listar	bi-graph-up-arrow
\.


--
-- TOC entry 5259 (class 0 OID 25045)
-- Dependencies: 248
-- Data for Name: pedidos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedidos (id, fecha, id_cliente, total, estado) FROM stdin;
3	2026-05-29 09:29:55.854178	1	55.38	PENDIENTE
4	2026-05-29 09:33:52.421499	1	73.55	COMPLETADO
5	2026-06-02 09:39:49.804741	1	56.87	COMPLETADO
6	2026-06-02 09:41:11.504917	1	253.58	COMPLETADO
7	2026-06-05 00:29:12.112245	1	41.47	PENDIENTE
1	2026-05-26 09:56:57.278906	1	8.90	COMPLETADO
8	2026-06-05 00:53:47.669246	2	72.65	COMPLETADO
9	2026-06-07 14:01:48.767612	15	85.11	PENDIENTE
10	2026-06-07 15:21:16.741573	15	363.06	COMPLETADO
2	2026-05-26 09:57:42.365026	1	110.14	CANCELADO
11	2026-06-09 09:30:19.0491	1	54.35	COMPLETADO
\.


--
-- TOC entry 5257 (class 0 OID 16622)
-- Dependencies: 246
-- Data for Name: perfil_opcion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.perfil_opcion (id_perfil, id_opcion) FROM stdin;
1	1
1	2
1	3
1	4
1	5
1	6
1	7
1	8
1	9
4	1
4	6
3	5
3	4
3	9
1	10
1	11
1	12
1	13
1	14
\.


--
-- TOC entry 5231 (class 0 OID 16402)
-- Dependencies: 220
-- Data for Name: perfiles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.perfiles (id, nombre, descripcion, estado) FROM stdin;
2	VENDEDOR	Acceso a ventas, catálogo y consultas de stock	1
3	ALMACENERO	Gestión de inventarios, entradas y salidas de productos	1
4	CAJERO	Relación con cuentas a pagar y cobrar	1
1	ADMINISTRADOR	Acceso total al sistema y gestión de usuarios	1
\.


--
-- TOC entry 5234 (class 0 OID 16420)
-- Dependencies: 223
-- Data for Name: perfiles_opciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.perfiles_opciones (id_perfil, id_opcion) FROM stdin;
\.


--
-- TOC entry 5244 (class 0 OID 16489)
-- Dependencies: 233
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.productos (id, nombre, id_categoria, id_proveedor, precio, stock, descripcion, estado, fecha_registro, imagen, precio_compra, precio_venta, stock_minimo) FROM stdin;
11	Extractor de resortes válvulas (14528)	4	1	158.78	1	Clave: CO-RE-VA, Uso rudo	1	2026-05-13 10:00:00	/images/products/a1104e7c-3e8e-4e44-95b0-b57e5a0556d0_compresor-para-resorte-de-valvulas-10-250mm-truper-14528.png	120.00	158.78	2
16	Juego de destornilladores 6 piezas (14140)	12	\N	45.50	5	Clave: DT-6X, Mangos ergonómicos Truper.	1	2026-06-06 13:38:22.989111	/images/products/e43b8c4e-f9a4-4fa4-9be3-2ea371e211e8_D_Q_NP_707707-MLA99954352293_112025-O.webp	35.00	45.50	10
6	Aceite sintético 2 tiempos (17625)	2	1	8.90	38	Clave: ACES-20, Contenido 400ml	1	2026-05-13 10:00:00	/images/products/7a02f215-006b-443a-a652-b8cdff80dbf7_D_Q_NP_705147-MLA79832932231_102024-.png	6.80	8.90	10
13	Flexómetro Gripper 5m (14578)	6	1	19.80	48	Clave: FH-5M, Cinta de 19mm	2	2026-05-13 10:00:00	/images/products/8e747b09-7856-4887-8539-ceeb473a96d7_imageUrl_1.webp	15.00	19.80	10
3	Alicate de corte diagonal 6" (17337)	1	1	15.68	25	Clave: T302-6X, Comfort Grip Expert	1	2026-05-13 10:00:00	/images/products/aacf4c4b-b353-47ea-b116-ca3076d39aba_alicate-de-corte-6-aislado-truper-17331.png	12.80	15.68	5
15	Matraca reversible 1/2" (13554)	7	1	41.60	12	Clave: M-549, Mango moleteado	1	2026-05-13 10:00:00	/images/products/2c14af9c-283f-44fe-8895-bc664602ddbd_images (1).jpg	32.00	41.60	3
14	Llave combinada 1/2" (12815)	7	1	11.25	37	Clave: LL-2016L, Acero al cromo vanadio	1	2026-05-13 10:00:00	/images/products/1213bf29-f92c-4719-9ff4-fcd90e96924f_133633.webp	8.50	11.25	10
2	Alicate de punta y corte 6" (17334)	1	1	15.68	24	Clave: T203-6X, Comfort Grip Expert	1	2026-05-13 10:00:00	/images/products/1c7636c8-0e97-4800-b470-9a0ac6b6c7ce_images.png	12.50	15.68	5
1	Alicate universal alta palanca 8" (17330)	1	1	26.69	27	Clave: T200-8X, Comfort Grip Expert	1	2026-05-13 10:00:00	/images/products/341fd6c8-bd30-460d-b719-6ccfa7f1c0f4_alicate-universal-8-truper-17330.webp	22.40	26.69	5
4	Alicate pelacables 22 a 10 AWG (17357)	1	1	16.00	17	Clave: PE-CA-6, Cortador de tornillos	1	2026-05-13 10:00:00	/images/products/646d3829-e515-4605-a5ea-10c888a83a8e_F_15666.jpg	13.50	16.00	5
9	Pistola silicona reforzada (101280)	3	1	12.75	41	Clave: PICA-R, Marca Truper	1	2026-05-13 10:00:00	/images/products/5910ec2d-23ad-4ef0-b186-57dd3c58ca64_image-493cadf1379b4169b669c1897e9a15bd.png	10.20	12.75	10
5	Aceite semi-sintético 4 tiempos (14929)	2	1	15.97	48	Clave: ACES-4T-32, Contenido 1L	1	2026-05-13 10:00:00	/images/products/4dc1e8b0-66df-4b0f-8ac9-6419b0fe6721_f70d6f0e9cc7d-2-1024x1024.png	12.50	15.97	10
12	Nivel magnético 24" (17056)	6	1	42.50	4	Clave: NT-24, Cuerpo de aluminio	1	2026-05-13 10:00:00	/images/products/4da20de9-6ae8-438b-b29d-1dac04f13fed_Nivel_magnetico_24_Truper_1024x1024.webp	35.00	42.50	5
7	Aceite aflojatodo Truper (13472)	2	1	10.17	98	Clave: WT-550, Contenido 550ml	1	2026-05-13 10:00:00	/images/products/ddfc0d74-f07d-4ecc-a288-dec87779f794_imageUrl_1.png	8.50	10.17	20
10	Compresor anillos de pistón (14534)	4	1	31.78	14	Clave: CO-RE-10, Apertura máx 5"	1	2026-05-13 10:00:00	/images/products/d7192131-a7f8-42b7-b0d4-1db631fd950c_D_NQ_NP_868614-MPE89427746867_082025-O.png	25.00	31.78	3
8	Pistola silicona tipo esqueleto (17550)	3	1	7.16	19	Clave: PICA-E, Marca Truper	2	2026-05-13 10:00:00	/images/products/77f42298-1c0f-4048-a180-c1c78ba03685_D_NQ_NP_792947-MPE89956195863_082025-O.png	5.50	7.16	12
\.


--
-- TOC entry 5240 (class 0 OID 16468)
-- Dependencies: 229
-- Data for Name: proveedores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proveedores (id, ruc, nombre, correo, direccion, estado, telefono, documento) FROM stdin;
1	20100480301	Truper Servicios S.A.	\N	Av. Los Chancas LT 8, Santa Anita	1	992223332	20609577321
\.


--
-- TOC entry 5236 (class 0 OID 16438)
-- Dependencies: 225
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, nombre, usuario, clave, id_perfil, correo, estado) FROM stdin;
2	Elizabeth Vega	gerente	$2a$10$3pUiRzo9Q2Y22Chx/mPaqu4DbaSEdkVR7Mzk0iiBLB26Gh2m/XOte	1	gerente@gmail.com	1
3	123	456	$2a$10$3pUiRzo9Q2Y22Chx/mPaqu4DbaSEdkVR7Mzk0iiBLB26Gh2m/XOte	2	ejemplo@gmail.com	2
6	Luz	luz	$2a$10$3pUiRzo9Q2Y22Chx/mPaqu4DbaSEdkVR7Mzk0iiBLB26Gh2m/XOte	2	luzs@gmail.com	1
10	Luz de Belen	lumon	$2a$10$3pUiRzo9Q2Y22Chx/mPaqu4DbaSEdkVR7Mzk0iiBLB26Gh2m/XOte	1	lumon@gmail.com	1
4	Ana	ana	$2a$10$3pUiRzo9Q2Y22Chx/mPaqu4DbaSEdkVR7Mzk0iiBLB26Gh2m/XOte	2	ana@gmail.com	2
1	Admin Luz	admin	$2a$10$3pUiRzo9Q2Y22Chx/mPaqu4DbaSEdkVR7Mzk0iiBLB26Gh2m/XOte	1	luz@gmail.com	1
\.


--
-- TOC entry 5248 (class 0 OID 16523)
-- Dependencies: 237
-- Data for Name: ventas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ventas (id, fecha, id_usuario, id_cliente, total, estado, tipo_comprobante, serie, numero_comprobante, subtotal, igv, estado_documento, comprobante_canje_id, nota_origen_id, afecta_inventario, metodo_pago, monto_efectivo, monto_tarjeta, monto_transferencia, monto_yape) FROM stdin;
1	2026-05-15 09:04:32.22945	1	1	26.14	1	BOLETA	B001	00000001	22.15	3.99	EMITIDA	\N	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
2	2026-05-15 09:15:22.09094	1	1	39.44	1	BOLETA	B001	00000002	33.42	6.02	EMITIDA	\N	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
3	2026-05-29 09:34:06.269656	1	1	73.55	1	BOLETA	B001	00000003	62.33	11.22	EMITIDA	\N	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
6	2026-06-05 09:09:06.387497	1	3	81.94	1	FACTURA	F001	00000006	69.44	12.50	EMITIDA	\N	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
4	2026-06-02 09:40:07.225592	1	1	56.87	1	NOTA DE VENTA	NV001	00000004	48.19	8.68	PENDIENTE	\N	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
5	2026-06-02 09:41:56.274722	1	1	253.58	1	NOTA DE VENTA	NV001	00000005	214.90	38.68	PENDIENTE	\N	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
11	2026-06-06 22:08:08.728385	1	1	72.65	1	BOLETA	B001	00000004	72.65	0.00	EMITIDA	\N	10	f	EFECTIVO	0.00	0.00	0.00	0.00
10	2026-06-06 22:03:20.196551	1	2	72.65	1	NOTA DE VENTA	NV001	00000010	72.65	0.00	CANJEADA	11	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
12	2026-06-07 11:50:19.509146	1	1	8.90	1	BOLETA	B001	00000005	8.90	0.00	EMITIDA	\N	9	f	EFECTIVO	0.00	0.00	0.00	0.00
9	2026-06-06 22:02:53.262844	1	1	8.90	1	NOTA DE VENTA	NV001	00000009	8.90	0.00	CANJEADA	12	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
14	2026-06-07 15:24:03.73806	1	15	363.06	1	BOLETA	B001	00000006	363.06	0.00	EMITIDA	\N	13	f	EFECTIVO	0.00	0.00	0.00	0.00
13	2026-06-07 15:22:47.16428	1	15	363.06	1	NOTA DE VENTA	NV001	00000011	363.06	0.00	CANJEADA	14	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
15	2026-06-07 17:41:11.247701	1	11	42.69	1	BOLETA	B001	00000007	42.69	0.00	EMITIDA	\N	8	f	EFECTIVO	0.00	0.00	0.00	0.00
8	2026-06-05 09:24:28.056397	1	11	42.69	1	NOTA DE VENTA	NV001	00000008	36.18	6.51	CANJEADA	15	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
7	2026-06-05 09:22:57.687352	1	10	28.43	1	NOTA DE VENTA	NV001	00000007	24.09	4.34	CANJEADA	16	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
16	2026-06-08 16:12:49.312486	1	10	28.43	0	BOLETA	B001	00000008	28.43	0.00	ANULADA	\N	7	f	EFECTIVO	0.00	0.00	0.00	0.00
18	2026-06-09 09:35:30.921385	1	1	54.35	1	BOLETA	B001	00000009	54.35	0.00	EMITIDA	\N	17	f	EFECTIVO	0.00	0.00	0.00	0.00
17	2026-06-09 09:31:38.219256	1	1	54.35	1	NOTA DE VENTA	NV001	00000012	54.35	0.00	CANJEADA	18	\N	t	EFECTIVO	0.00	0.00	0.00	0.00
\.


--
-- TOC entry 5286 (class 0 OID 0)
-- Dependencies: 253
-- Name: caja_sesion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.caja_sesion_id_seq', 2, true);


--
-- TOC entry 5287 (class 0 OID 0)
-- Dependencies: 230
-- Name: categorias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categorias_id_seq', 14, true);


--
-- TOC entry 5288 (class 0 OID 0)
-- Dependencies: 226
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clientes_id_seq', 15, true);


--
-- TOC entry 5289 (class 0 OID 0)
-- Dependencies: 242
-- Name: cuentas_cobrar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuentas_cobrar_id_seq', 5, true);


--
-- TOC entry 5290 (class 0 OID 0)
-- Dependencies: 244
-- Name: cuentas_pagar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuentas_pagar_id_seq', 1, true);


--
-- TOC entry 5291 (class 0 OID 0)
-- Dependencies: 249
-- Name: detalles_pedidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalles_pedidos_id_seq', 32, true);


--
-- TOC entry 5292 (class 0 OID 0)
-- Dependencies: 234
-- Name: detalles_tecnicos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalles_tecnicos_id_seq', 1, false);


--
-- TOC entry 5293 (class 0 OID 0)
-- Dependencies: 238
-- Name: detalles_ventas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalles_ventas_id_seq', 42, true);


--
-- TOC entry 5294 (class 0 OID 0)
-- Dependencies: 240
-- Name: inventario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_id_seq', 28, true);


--
-- TOC entry 5295 (class 0 OID 0)
-- Dependencies: 251
-- Name: notificaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notificaciones_id_seq', 32, true);


--
-- TOC entry 5296 (class 0 OID 0)
-- Dependencies: 221
-- Name: opciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.opciones_id_seq', 14, true);


--
-- TOC entry 5297 (class 0 OID 0)
-- Dependencies: 247
-- Name: pedidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedidos_id_seq', 11, true);


--
-- TOC entry 5298 (class 0 OID 0)
-- Dependencies: 219
-- Name: perfiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.perfiles_id_seq', 4, true);


--
-- TOC entry 5299 (class 0 OID 0)
-- Dependencies: 232
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.productos_id_seq', 16, true);


--
-- TOC entry 5300 (class 0 OID 0)
-- Dependencies: 228
-- Name: proveedores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proveedores_id_seq', 1, false);


--
-- TOC entry 5301 (class 0 OID 0)
-- Dependencies: 224
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 10, true);


--
-- TOC entry 5302 (class 0 OID 0)
-- Dependencies: 236
-- Name: ventas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ventas_id_seq', 18, true);


--
-- TOC entry 5052 (class 2606 OID 33265)
-- Name: caja_sesion caja_sesion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caja_sesion
    ADD CONSTRAINT caja_sesion_pkey PRIMARY KEY (id);


--
-- TOC entry 5014 (class 2606 OID 16719)
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- TOC entry 5002 (class 2606 OID 16466)
-- Name: clientes clientes_dni_ruc_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_dni_ruc_key UNIQUE (dni_ruc);


--
-- TOC entry 5004 (class 2606 OID 24886)
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- TOC entry 5031 (class 2606 OID 33196)
-- Name: cuentas_cobrar cuentas_cobrar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas_cobrar
    ADD CONSTRAINT cuentas_cobrar_pkey PRIMARY KEY (id);


--
-- TOC entry 5033 (class 2606 OID 33204)
-- Name: cuentas_pagar cuentas_pagar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas_pagar
    ADD CONSTRAINT cuentas_pagar_pkey PRIMARY KEY (id);


--
-- TOC entry 5041 (class 2606 OID 25074)
-- Name: detalles_pedidos detalles_pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_pedidos
    ADD CONSTRAINT detalles_pedidos_pkey PRIMARY KEY (id);


--
-- TOC entry 5018 (class 2606 OID 16516)
-- Name: detalles_tecnicos detalles_tecnicos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_tecnicos
    ADD CONSTRAINT detalles_tecnicos_pkey PRIMARY KEY (id);


--
-- TOC entry 5025 (class 2606 OID 24907)
-- Name: detalles_ventas detalles_ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_ventas
    ADD CONSTRAINT detalles_ventas_pkey PRIMARY KEY (id);


--
-- TOC entry 5029 (class 2606 OID 16572)
-- Name: inventario inventario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT inventario_pkey PRIMARY KEY (id);


--
-- TOC entry 5050 (class 2606 OID 33224)
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);


--
-- TOC entry 4992 (class 2606 OID 16611)
-- Name: opciones opciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.opciones
    ADD CONSTRAINT opciones_pkey PRIMARY KEY (id);


--
-- TOC entry 5039 (class 2606 OID 25056)
-- Name: pedidos pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id);


--
-- TOC entry 5035 (class 2606 OID 16628)
-- Name: perfil_opcion perfil_opcion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfil_opcion
    ADD CONSTRAINT perfil_opcion_pkey PRIMARY KEY (id_perfil, id_opcion);


--
-- TOC entry 4994 (class 2606 OID 16426)
-- Name: perfiles_opciones perfiles_opciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfiles_opciones
    ADD CONSTRAINT perfiles_opciones_pkey PRIMARY KEY (id_perfil, id_opcion);


--
-- TOC entry 4990 (class 2606 OID 16631)
-- Name: perfiles perfiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfiles
    ADD CONSTRAINT perfiles_pkey PRIMARY KEY (id);


--
-- TOC entry 5016 (class 2606 OID 16694)
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- TOC entry 5008 (class 2606 OID 16759)
-- Name: proveedores proveedores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT proveedores_pkey PRIMARY KEY (id);


--
-- TOC entry 5010 (class 2606 OID 16478)
-- Name: proveedores proveedores_ruc_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT proveedores_ruc_key UNIQUE (ruc);


--
-- TOC entry 4996 (class 2606 OID 16678)
-- Name: usuarios ukcdmw5hxlfj78uf4997i3qyyw5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukcdmw5hxlfj78uf4997i3qyyw5 UNIQUE (correo);


--
-- TOC entry 5012 (class 2606 OID 24883)
-- Name: proveedores ukffj6y49mpe4t7pj6klbksla0t; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT ukffj6y49mpe4t7pj6klbksla0t UNIQUE (documento);


--
-- TOC entry 5006 (class 2606 OID 24970)
-- Name: clientes ukm6ysdwsqke00e5piajbvgn6lg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT ukm6ysdwsqke00e5piajbvgn6lg UNIQUE (dni);


--
-- TOC entry 4998 (class 2606 OID 16649)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 5000 (class 2606 OID 16449)
-- Name: usuarios usuarios_usuario_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_usuario_key UNIQUE (usuario);


--
-- TOC entry 5023 (class 2606 OID 24933)
-- Name: ventas ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT ventas_pkey PRIMARY KEY (id);


--
-- TOC entry 5042 (class 1259 OID 25087)
-- Name: idx_detalles_pedidos_pedido; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_detalles_pedidos_pedido ON public.detalles_pedidos USING btree (id_pedido);


--
-- TOC entry 5043 (class 1259 OID 25088)
-- Name: idx_detalles_pedidos_producto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_detalles_pedidos_producto ON public.detalles_pedidos USING btree (id_producto);


--
-- TOC entry 5026 (class 1259 OID 25039)
-- Name: idx_detalles_ventas_producto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_detalles_ventas_producto ON public.detalles_ventas USING btree (id_producto);


--
-- TOC entry 5027 (class 1259 OID 25038)
-- Name: idx_detalles_ventas_venta; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_detalles_ventas_venta ON public.detalles_ventas USING btree (id_venta);


--
-- TOC entry 5044 (class 1259 OID 33253)
-- Name: idx_notificaciones_cuenta_cobrar; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notificaciones_cuenta_cobrar ON public.notificaciones USING btree (id_cuenta_cobrar);


--
-- TOC entry 5045 (class 1259 OID 33254)
-- Name: idx_notificaciones_cuenta_pagar; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notificaciones_cuenta_pagar ON public.notificaciones USING btree (id_cuenta_pagar);


--
-- TOC entry 5046 (class 1259 OID 33251)
-- Name: idx_notificaciones_pedido; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notificaciones_pedido ON public.notificaciones USING btree (id_pedido);


--
-- TOC entry 5047 (class 1259 OID 33252)
-- Name: idx_notificaciones_producto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notificaciones_producto ON public.notificaciones USING btree (id_producto);


--
-- TOC entry 5048 (class 1259 OID 33250)
-- Name: idx_notificaciones_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notificaciones_usuario ON public.notificaciones USING btree (id_usuario);


--
-- TOC entry 5036 (class 1259 OID 25085)
-- Name: idx_pedidos_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pedidos_cliente ON public.pedidos USING btree (id_cliente);


--
-- TOC entry 5037 (class 1259 OID 25086)
-- Name: idx_pedidos_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pedidos_fecha ON public.pedidos USING btree (fecha);


--
-- TOC entry 5019 (class 1259 OID 25036)
-- Name: idx_ventas_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ventas_cliente ON public.ventas USING btree (id_cliente);


--
-- TOC entry 5020 (class 1259 OID 25037)
-- Name: idx_ventas_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ventas_fecha ON public.ventas USING btree (fecha);


--
-- TOC entry 5021 (class 1259 OID 25035)
-- Name: idx_ventas_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ventas_usuario ON public.ventas USING btree (id_usuario);


--
-- TOC entry 5081 (class 2620 OID 25043)
-- Name: ventas trg_kardex_venta_cancel; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_kardex_venta_cancel AFTER UPDATE ON public.ventas FOR EACH ROW EXECUTE FUNCTION public.fn_automatizar_kardex_cancelacion();


--
-- TOC entry 5082 (class 2620 OID 25041)
-- Name: detalles_ventas trg_kardex_venta_insert; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_kardex_venta_insert AFTER INSERT ON public.detalles_ventas FOR EACH ROW EXECUTE FUNCTION public.fn_automatizar_kardex_venta();


--
-- TOC entry 5066 (class 2606 OID 24989)
-- Name: cuentas_cobrar cuentas_cobrar_id_cliente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas_cobrar
    ADD CONSTRAINT cuentas_cobrar_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.clientes(id);


--
-- TOC entry 5067 (class 2606 OID 24994)
-- Name: cuentas_cobrar cuentas_cobrar_id_venta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas_cobrar
    ADD CONSTRAINT cuentas_cobrar_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES public.ventas(id);


--
-- TOC entry 5068 (class 2606 OID 25003)
-- Name: cuentas_pagar cuentas_pagar_id_proveedor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas_pagar
    ADD CONSTRAINT cuentas_pagar_id_proveedor_fkey FOREIGN KEY (id_proveedor) REFERENCES public.proveedores(id);


--
-- TOC entry 5058 (class 2606 OID 25012)
-- Name: detalles_tecnicos detalles_tecnicos_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_tecnicos
    ADD CONSTRAINT detalles_tecnicos_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id) ON DELETE CASCADE;


--
-- TOC entry 5063 (class 2606 OID 24913)
-- Name: detalles_ventas detalles_ventas_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_ventas
    ADD CONSTRAINT detalles_ventas_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 5064 (class 2606 OID 24940)
-- Name: detalles_ventas detalles_ventas_id_venta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_ventas
    ADD CONSTRAINT detalles_ventas_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES public.ventas(id) ON DELETE CASCADE;


--
-- TOC entry 5074 (class 2606 OID 33225)
-- Name: notificaciones fk118snjfqiuksspw6jf20a26un; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fk118snjfqiuksspw6jf20a26un FOREIGN KEY (id_cuenta_cobrar) REFERENCES public.cuentas_cobrar(id);


--
-- TOC entry 5079 (class 2606 OID 33272)
-- Name: caja_sesion fk1t550m1bcla5hf0fw3r0vhgpa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caja_sesion
    ADD CONSTRAINT fk1t550m1bcla5hf0fw3r0vhgpa FOREIGN KEY (id_usuario_cierre) REFERENCES public.usuarios(id);


--
-- TOC entry 5059 (class 2606 OID 33170)
-- Name: ventas fk2gfqsmc4ivr9f6bsm5jkidgvp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fk2gfqsmc4ivr9f6bsm5jkidgvp FOREIGN KEY (nota_origen_id) REFERENCES public.ventas(id);


--
-- TOC entry 5080 (class 2606 OID 33267)
-- Name: caja_sesion fk2k7rj7y6cj87f1bjph2bit5yh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caja_sesion
    ADD CONSTRAINT fk2k7rj7y6cj87f1bjph2bit5yh FOREIGN KEY (id_usuario_apertura) REFERENCES public.usuarios(id);


--
-- TOC entry 5075 (class 2606 OID 33230)
-- Name: notificaciones fk8q7wkwxhvafmeniyk8m66trcg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fk8q7wkwxhvafmeniyk8m66trcg FOREIGN KEY (id_cuenta_pagar) REFERENCES public.cuentas_pagar(id);


--
-- TOC entry 5076 (class 2606 OID 33235)
-- Name: notificaciones fk94jjjxqiadx0oar7aq6l71rul; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fk94jjjxqiadx0oar7aq6l71rul FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id);


--
-- TOC entry 5072 (class 2606 OID 25075)
-- Name: detalles_pedidos fk_detalles_pedido; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_pedidos
    ADD CONSTRAINT fk_detalles_pedido FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id) ON DELETE CASCADE;


--
-- TOC entry 5073 (class 2606 OID 25080)
-- Name: detalles_pedidos fk_detalles_producto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_pedidos
    ADD CONSTRAINT fk_detalles_producto FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 5071 (class 2606 OID 25057)
-- Name: pedidos fk_pedidos_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk_pedidos_cliente FOREIGN KEY (id_cliente) REFERENCES public.clientes(id);


--
-- TOC entry 5069 (class 2606 OID 16679)
-- Name: perfil_opcion fkccootfr17pdgjedgifd92qao0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfil_opcion
    ADD CONSTRAINT fkccootfr17pdgjedgifd92qao0 FOREIGN KEY (id_opcion) REFERENCES public.opciones(id);


--
-- TOC entry 5070 (class 2606 OID 16684)
-- Name: perfil_opcion fke1pcyxsiyjjqt8g486euwsxft; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfil_opcion
    ADD CONSTRAINT fke1pcyxsiyjjqt8g486euwsxft FOREIGN KEY (id_perfil) REFERENCES public.perfiles(id);


--
-- TOC entry 5060 (class 2606 OID 33165)
-- Name: ventas fkintesrscyfd1jwt0gripdrdg2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fkintesrscyfd1jwt0gripdrdg2 FOREIGN KEY (comprobante_canje_id) REFERENCES public.ventas(id);


--
-- TOC entry 5077 (class 2606 OID 33240)
-- Name: notificaciones fkoe0g7rt9q2it7m9v1ybeglrya; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fkoe0g7rt9q2it7m9v1ybeglrya FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 5078 (class 2606 OID 33245)
-- Name: notificaciones fkrr0ikjdv4qycj44q3lohskm4k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fkrr0ikjdv4qycj44q3lohskm4k FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- TOC entry 5065 (class 2606 OID 24976)
-- Name: inventario inventario_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT inventario_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 5053 (class 2606 OID 16613)
-- Name: perfiles_opciones perfiles_opciones_id_opcion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfiles_opciones
    ADD CONSTRAINT perfiles_opciones_id_opcion_fkey FOREIGN KEY (id_opcion) REFERENCES public.opciones(id);


--
-- TOC entry 5054 (class 2606 OID 16633)
-- Name: perfiles_opciones perfiles_opciones_id_perfil_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfiles_opciones
    ADD CONSTRAINT perfiles_opciones_id_perfil_fkey FOREIGN KEY (id_perfil) REFERENCES public.perfiles(id);


--
-- TOC entry 5056 (class 2606 OID 16735)
-- Name: productos productos_id_categoria_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_id_categoria_fkey FOREIGN KEY (id_categoria) REFERENCES public.categorias(id);


--
-- TOC entry 5057 (class 2606 OID 16766)
-- Name: productos productos_id_proveedor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_id_proveedor_fkey FOREIGN KEY (id_proveedor) REFERENCES public.proveedores(id);


--
-- TOC entry 5055 (class 2606 OID 16665)
-- Name: usuarios usuarios_id_perfil_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_id_perfil_fkey FOREIGN KEY (id_perfil) REFERENCES public.perfiles(id);


--
-- TOC entry 5061 (class 2606 OID 24951)
-- Name: ventas ventas_id_cliente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT ventas_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.clientes(id);


--
-- TOC entry 5062 (class 2606 OID 24960)
-- Name: ventas ventas_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT ventas_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


-- Completed on 2026-07-15 15:53:09

--
-- PostgreSQL database dump complete
--

\unrestrict o03f5XVRXCoocBTqcOgTJahNsaiXk5onsEV6crVbT7hKuT2S5dgG7pepmLlegR9

