# URL de conexión (asegúrate que el puerto sea 5432 y el nombre de la BD coincida)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/gestion_pernos}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:123456}

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API de consulta DNI (RENIEC) y RUC (SUNAT)
consulta.api.proveedor=decolecta
consulta.api.token=${CONSULTA_API_TOKEN:sk_16166.3QFVbnaC3SYPDBuqUDS0Rc3Xd75YkH71}
consulta.api.url=https://api.decolecta.com/v1

# Configuración de CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:8080}
