# URL de conexión (asegúrate que el puerto sea 5432 y el nombre de la BD coincida)
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_pernos
spring.datasource.username=postgres
spring.datasource.password=123456

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
# 'update' creará las tablas si no existen, pero no borrará tus datos.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect